### ISSUE TITLE
Duplicated resources with search widget

### ISSUE THREAD

**Issue by jalonsoReservamos** [reservamos/item-quantity-dropdown#8]
La carga de estas fuentes causa una carga duplicada de recursos cuando se utiliza este componente en el search-widget. 

https://github.com/reservamos/item-quantity-dropdown/blob/3faa5c9f22b6d39d98dd092778a3cbda018c267d/src/styles/lib/helpers/_design-system.scss#L4

**Comment by oquis** [comment]
Arreglado en esta versión https://github.com/reservamos/item-quantity-dropdown/releases/tag/v2.0.2
